# Generated by Django 4.0.6 on 2023-01-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_pricediscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='product',
            order_with_respect_to='discount',
        ),
    ]
