# Generated by Django 4.0.6 on 2023-02-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('type', models.CharField(max_length=150, null=True)),
                ('message', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(null=True, upload_to='banner/')),
                ('minPrice', models.PositiveIntegerField(null=True)),
                ('maxPrice', models.PositiveIntegerField(null=True)),
                ('minDiscount', models.PositiveIntegerField(null=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic')),
            ],
        ),
    ]
